export interface IUser {
  'login': 'ssk-dev',
  'id': 24464850,
  'node_id': 'MDQ6VXNlcjI0NDY0ODUw',
  'avatar_url': 'https://avatars3.githubusercontent.com/u/24464850?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/ssk-dev',
  'html_url': 'https://github.com/ssk-dev',
  'followers_url': 'https://api.github.com/users/ssk-dev/followers',
  'following_url': 'https://api.github.com/users/ssk-dev/following{/other_user}',
  'gists_url': 'https://api.github.com/users/ssk-dev/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/ssk-dev/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/ssk-dev/subscriptions',
  'organizations_url': 'https://api.github.com/users/ssk-dev/orgs',
  'repos_url': 'https://api.github.com/users/ssk-dev/repos',
  'events_url': 'https://api.github.com/users/ssk-dev/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/ssk-dev/received_events',
  'type': 'User',
  'site_admin': false,
  'name': 'Sebastian Schulze-Khyi',
  'company': null,
  'blog': '',
  'location': 'Germany',
  'email': 's.schulze@its-cooperation.de',
  'hireable': null,
  'bio': null,
  'public_repos': 20,
  'public_gists': 2,
  'followers': 1,
  'following': 2,
  'created_at': '2016-12-08T22:36:23Z',
  'updated_at': '2019-10-28T10:57:02Z',
  'private_gists': 0,
  'total_private_repos': 3,
  'owned_private_repos': 3,
  'disk_usage': 21214,
  'collaborators': 0,
  'two_factor_authentication': true,
  'plan': {
    'name': 'free',
    'space': 976562499,
    'collaborators': 0,
    'private_repos': 10000
  }
}
